# Generated by Django 2.2.2 on 2020-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportclubmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
