# Generated by Django 2.2.2 on 2020-04-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturdays', models.BooleanField(default=False)),
                ('sundays', models.BooleanField(default=False)),
                ('mondays', models.BooleanField(default=False)),
                ('tuesdays', models.BooleanField(default=False)),
                ('wednesdays', models.BooleanField(default=False)),
                ('thursdays', models.BooleanField(default=False)),
                ('fridays', models.BooleanField(default=False)),
                ('range_start_day', django_jalali.db.models.jDateField()),
                ('range_end_day', django_jalali.db.models.jDateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at_date', django_jalali.db.models.jDateField(max_length=264, null=True)),
                ('created_at_time', models.TimeField(max_length=264, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessioncategories', to='salon.SalonModel')),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_booker_name', models.CharField(max_length=264, null=True)),
                ('day', django_jalali.db.models.jDateField(null=True)),
                ('day_str', models.CharField(max_length=264)),
                ('time', models.TimeField(null=True)),
                ('duration', models.CharField(max_length=264)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discount_percentage', models.FloatField(default=0)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('booker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='salon.SalonModel')),
                ('session_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='session.SessionCategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='LastDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_length', models.IntegerField(blank=True, null=True)),
                ('first_day', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('first_day_2', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('last_day', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('last_saturday', models.BooleanField(default=False)),
                ('last_sunday', models.BooleanField(default=False)),
                ('last_monday', models.BooleanField(default=False)),
                ('last_tuesday', models.BooleanField(default=False)),
                ('last_wednesday', models.BooleanField(default=False)),
                ('last_thursday', models.BooleanField(default=False)),
                ('last_friday', models.BooleanField(default=False)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lastdatas', to='salon.SalonModel')),
            ],
        ),
    ]
