# Generated by Django 2.2.2 on 2019-10-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonusermodel',
            name='picture',
        ),
    ]
