# Generated by Django 2.2.2 on 2020-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonusermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
