# Generated by Django 2.2.2 on 2020-05-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonuser', '0002_auto_20200518_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonusermodel',
            name='phone_number',
        ),
    ]
