# Generated by Django 2.2.2 on 2020-05-18 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonuser', '0003_remove_commonusermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonusermodel',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='commonusers', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
