from django.urls import include, path
from sportclub.views import (SportClubSignupView, SportClubProfileView,
                            SportClubListView, SportClubDetailView,
                            BannedSportClubListView, SportClubBanView,
                            SportClubDeleteView,SportClubUnBanView,
                            BannedSportClubExceptionView, MesssageSendingView,
                            EmailSendingView, BankInfoChangeView,
                            SportClubUpdateView, TermsAndConditionsView,
                            SportClubListViewSuperUser,SportClubDetailViewSuperUser,
                            SportClubWorkSpaceView,SportClubDetailsView,
                            SportClubBanView_2,SportClubUnBanView_2,
                            SportClubBanView_3,SportClubUnBanView_3,BanModalView,
                            UnBanModalView,UnBanModalView_2,UnBanModalView_3,
                            BanModalView_2,BanModalView_3, MapDataSetView, MapView,
                            NoAccountDetailErrorView, SportClubPublicListView,
                            SportClubPublicDetailView, )
from salon.views import SalonCreateView

app_name ='sportclub'
urlpatterns = [
    path('signup/', SportClubSignupView, name='signup'),
    path('no-account-detail-eroor/', NoAccountDetailErrorView.as_view(), name='noaccountdetailerror'),
    path('map-datasets/', MapDataSetView, name='mapdataset'),
    path('map/', MapView, name='map'),
    path('profile/<slug:slug>/', SportClubProfileView, name='profile'),
    path('workspace/<slug:slug>/', SportClubWorkSpaceView, name='workspace'),
    path('list/', SportClubListView, name='list'),
    path('list-superuser/', SportClubListViewSuperUser, name='listforsuperuser'),
    path('Plist/', SportClubPublicListView, name='publiclist'),
    path('detail-superuser/<slug:slug>/', SportClubDetailViewSuperUser, name='detailforsuperuser'),
    path('bannedlist/', BannedSportClubListView, name='bannedlist'),
    path('list/<slug:slug>/', SportClubDetailView, name='detail'),
    path('Pdetail/<int:pk>/', SportClubPublicDetailView, name='publicdetail'),
    path('public-detail/<int:pk>/', SportClubDetailsView, name='publicdetail'),
    path('ban/<slug:slug>/', SportClubBanView, name='ban'),
    path('ban-modal/<slug:slug>/', BanModalView, name='banmodal'),
    path('ban-modal-2/<slug:slug>/', BanModalView_2, name='banmodal2'),
    path('ban-modal-3/<slug:slug>/', BanModalView_3, name='banmodal3'),
    path('ban-2/<slug:slug>/', SportClubBanView_2, name='ban_2'),
    path('ban-3/<slug:slug>/', SportClubBanView_3, name='ban_3'),
    path('unban/<slug:slug>/', SportClubUnBanView, name='unban'),
    path('unban-modal/<slug:slug>/', UnBanModalView, name='unbanmodal'),
    path('unban-modal-2/<slug:slug>/', UnBanModalView_2, name='unbanmodal2'),
    path('unban-modal-3/<slug:slug>/', UnBanModalView_3, name='unbanmodal3'),
    path('unban-2/<slug:slug>/', SportClubUnBanView_2, name='unban_2'),
    path('unban-3/<slug:slug>/', SportClubUnBanView_3, name='unban_3'),
    path('delete/<slug:slug>/', SportClubDeleteView, name='delete'),
    path('salon/bannedsportclub/<slug:slug>',BannedSportClubExceptionView,
         name='bannedsportclubexception'),
    path('sendsms/<slug:slug>/',MesssageSendingView, name='sendsms'),
    path('sendemail/<slug:slug>/',EmailSendingView, name='sendemail'),
    path('bankinfochange/<slug:slug>/', BankInfoChangeView, name='bankinfochange'),
    path('update/<slug:slug>/', SportClubUpdateView, name='update'),
    path('termsandconditions/<slug:slug>/', TermsAndConditionsView, name='termsandconditions'),


]
